export const types = {
  CHANGE_TITLE: 'CHANGE_TITLE',
  WITH_PARAMS: "WITH_PARAMS",
  VALUE: "VALUE",
  ADD_USER: 'ADD_USER',
  DELETE_ALL: "DELETE_ALL",
  ADD_NUMBER: "ADD_NUMBER",
  CLEAR_ALL: "CLEAR_ALL",
  PRELOADER_ON: "PRELOADER_ON",
  PRELOADER_OFF: "PRELOADER_OFF",
  USER_REQUEST: "USER_REQUEST",
  USER_SUCCES: "USER_SUCCES",
  USER_ERROR: "USER_ERROR",
  ALERT_ON: "ALERT_ON",
  ALERT_OFF: "ALERT_OFF"


}

